Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true

  # 日本語でのコメントを許可
AsciiComments:
  Enabled: false

  # 最大文字数
Metrics/LineLength:
  Max: 120

  # 以下のファイルはブロックの文字数チェックはしない
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

  # {}のスペースがあることをチェック
Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

  # コンパクト形式でクラスを宣言
ClassAndModuleChildren:
  EnforcedStyle: compact