name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: root
        ports:
          - 3306

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: mysql set up
        run: sudo apt-get install libmysqlclient-dev

      - name: yarn install
        run: yarn install

      - name: Build and test with rails
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails
          echo '成功！！！！'

        - name: db create
        run: bundle exec rails db:create

      - name: Run rubocop
        run: bundle exec rubocop

      - name: Run rspec
        run: bundle exec rspec
